language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - PATH=$PATH:/home/travis/.cargo/bin
  - cargo install rustfmt

script:
  - cargo fmt checkstyle
  - cargo build --verbose
