[package]

name = "beamium"
version = "1.0.1"
authors = [ "d33d33 <kevin@d33d33.fr>" ]

[dependencies]
clap = "2.19.2"
yaml-rust = "0.3.5"
cast = "0.1.0"
nix = "0.7.0"
time = "0.1.35"
hyper = "0.9.14"
regex = "0.1.80"
slog = "1.2"
slog-term = "1.3.3"
slog-stream = "1.2.0"
slog-json = "1.2.1"
slog-scope = "0.2.2"
